name: Build and deploy action
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Копируем код из репозитория в runner
      - name: clone code
        uses: actions/checkout@v2
#	  # Собираем
#      - name: docker build
#        #run: docker build -t my-image .
#        run: docker build -t snz2010/lesson26:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
#      - name: docker login
#        run:
#      - name: docker push
#        run:

